version: '3.8'

services:
  postgres:
    image: postgres:14.4-alpine
    volumes:
      - data-auth:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../static/:/var/html/static/
      - ../../media/:/var/html/media/



volumes:
  data-auth:
